apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "etcd-defrag.fullname" . }}
  labels: {{ include "etcd-defrag.labels" . | nindent 4 }}
rules:
  # We need to be able to list pods and to exec
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - watch
      - get
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - get
      - create
